### ISSUE TITLE
No warnings for invalid pointer arithmetic

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#10]
Source code:
```c
#include <stdio.h>

int main()
{
  int x;
  &x + 2;
}
```

tis-interpreter (c82b0fdfc2fb4ba9bdec9b59f935b49d6059c0bc) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed
[value] done for function main
```

For the purposes of pointer arithmetic, an ordinary variable behaves as an array of length one. So going beyond &x + 1 is not permitted.

**Comment by ch3root** [comment]
To get rid of void context:

Source code:
```c
#include <stdio.h>

int main()
{
  int x;
  int *p = &x + 2;
  printf("%d\n", p > &x);
}
```

tis-interpreter (c82b0fdfc2fb4ba9bdec9b59f935b49d6059c0bc) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed
10.c:7:[kernel] warning: pointer comparison: assert \pointer_comparable((void *)p, (void *)(&x));
                  stack: main
[value] Stopping at nth alarm
[value] user error: Degeneration occurred:
                    results are not correct for lines of code that can be reached from the degeneration point.
```

This is another kind of warnings.

**Comment by pascal-cuoq** [comment]
OOB pointer arithmetic detection only needed to be enabled ([shortest commit ever](https://github.com/TrustInSoft/tis-interpreter/commit/b29cc8acdf534259506ba439f6fa74e367619fe6)).

For now, OOB pointer arithmetic does not interrupt execution, so that you would get both warnings on your second example, the warning for `&x + 2` and the warning for `p > &x`. I hope you don't mind. The behavior will be made more consistent later.

**Comment by ch3root** [comment]
Cool! Not terminating the execution in this case seems even better than terminating.

The only inconvenience is that the message `[value] warning: pointer arithmetic going out of bounds. assert(pointer valid or one-past)` doesn't indicate problematic operator when there is a large expression with many operators.
