### ISSUE TITLE
No warning: storing a trap representation into _Bool

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#101]
Source code:
```c
#include <stdio.h>

int main()
{
  _Bool b;
  *(char *)&b = 123;
  printf("%d\n", *(char *)&b);
}
```

tis-interpreter (d4961d3fa420ebd5b895e7c54636acae8ada344e) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed

123

[value] done for function main
```

gcc (GCC) 7.0.0 20160528 (experimental):
```
$ gcc -std=c11 -pedantic -Wall -Wextra -O3 test.c && ./a.out
1
```

clang version 3.9.0 (trunk 271117):
```
$ clang -std=c11 -Weverything -O3 test.c && ./a.out
123
```

**Comment by pascal-cuoq** [comment]
I am not convinced yet that this example invokes undefined behavior (as opposed to “reveals a GCC bug where the compiler is over-enthusiastic about what its developers think might be undefined behavior”). That may be because so few types have trap representations and I do not regularly deal with them.

It used to seem to me that the following could be said to be true:

- every object of complete type `t` has a representation, which can be seen as an array of `sizeof(t)` chars. `sizeof(t) > 1` because objects are not allowed to have size 0.
- accessing what is for type `t` a trap representation, through an lvalue of type `t`, is undefined behavior, but the representation can be written to and read from as the char array that it implicitly is. If it is written to and then read from using an lvalue of type `char` without intervening access through an lvalue of type `t`, no UB occurs.

In fact I don't even know what part of the standard the GCC developers thinks they are invoking here. Is it strict aliasing, because although a `char` lvalue is used to access `b`, the character written does not come from the representation? Apparently not, according to [this test](https://godbolt.org/g/eybvjf). Do they see the UB as happening on the write through `*(char *)&b`? Does that mean that the same program without the last line invokes UB too?

**Comment by ch3root** [comment]
I guess nobody has much experience with trap representations:-)

I don't think this is UB, just code giving unspecified value. I'm not sure to what degree this is permitted by the C standard or that this is done in gcc intentionally but I can imagine the following logic. C11, 6.2.6.2p1, reads: "The values of any padding bits are unspecified." With some will, this could be taken as meaning that the padding is permanently unspecified. That is, it's unspecified even if you store to it explicitly.

Not sure if it clears anything or muddies, but [x86-64 ABI](http://x86-64.org/documentation/abi.pdf) says: "Booleans, when stored in a memory object, are stored as single byte objects the value of which is always 0 (false) or 1 (true)."

Another POV: Committee Response for Question 1 in DR 260 reads: "Values may have any bit-pattern that validly represents them and the implementation is free to move between alternate representations (for example, it may normalize pointers, floating-point representations etc.). [...] the actual bit-pattern may change without direct action of the program." Isn't this wonderful?

(It's a pity tis-interpreter doesn't support i386 or long double. We could discuss how assignment changes floating point numbers.)

**Comment by PetteriAimonen** [comment]
This is somewhat related also, and is a case where I have myself been bit by this bool 0/1 issue: http://stackoverflow.com/questions/27661768/weird-results-for-conditional-operator-with-gcc-and-bool-pointers

This is particularly annoying when trying to guard against untrusted data in a struct that contains bool fields. I happen to have such a test in my test suite, and the newest tis-interpreter snapshot does catch it: "warning: Reading a wrong representation ({32}) for type _Bool." Seems like correct behaviour for tis-interpreter, and I'll have to do something about my handling of bool fields.

**Comment by PetteriAimonen** [comment]
Ah, now I see that this issue is about whether the wrong value is actually a trap value, or, just undefined behaviour once reading it back as bool. Sorry for interrupting :)

**Comment by pascal-cuoq** [comment]
@PetteriAimonen That SO question is more like https://github.com/TrustInSoft/tis-interpreter/issues/39, which has been fixed. I cannot try it myself right now, but I believe that the lastest version of tis-interpreter should say that something is wrong in the example from that question.

**Comment by PetteriAimonen** [comment]
@pascal-cuoq Yes, it does. I just initially missed the difference between these two issues :)

**Comment by ch3root** [comment]
This specific issue turned out to be considered a bug in gcc -- https://gcc.gnu.org/ml/gcc/2016-06/msg00046.html .

**Comment by pascal-cuoq** [comment]
Should this issue be closed?

**Comment by ch3root** [comment]
Yes, I think this can be closed.
