### ISSUE TITLE
Support uint128_t

### ISSUE THREAD

**Issue by ysangkok** [TrustInSoft/tis-interpreter#141]
I tried using the TIS Interpreter on libsecp256k1, it didn't work because of lacking uint128_t support. I know this is not standard C, but since GCC supports it, I wonder if it could be added.

**Comment by pascal-cuoq** [comment]
Hello,

In principle, adding `int128_t` and `uint128_t` is not too hard: TIS Interpreter is already using bignums for everything internally, so it may seem a straightforward improvement to add extra integer types with width 128 bits and range -2^127...2^127-1 (and respectively 0..2^128-1).

One of the difficulties with this improvement is reverse-engineering (because this will not have been documented at the level of detail we'll need) and emulating exactly the behavior of the new type with respect to:

- the typing of integer constants: https://port70.net/~nsz/c/c11/n1570.html#6.4.4.1

- usual arithmetic conversions: https://port70.net/~nsz/c/c11/n1570.html#6.3.1.8

- conversion specifiers and `printf`/`scanf`

- ...?

What we have done so far to work around the problem when it occurred was to use the pure C implementation, which was always present in the crypto libraries we looked at. I will try to see if it is possible to add minimal support for `uint128_t`, without promising perfect emulation of the GCC extension.

**Comment by pascal-cuoq** [comment]
Hello again,

exactly the kind of minimal support for 128-bit integer types I was describing has already been implemented in https://github.com/TrustInSoft/tis-kernel (which is basically TIS Interpreter but kept in better sync with developments at TrustInSoft).

If you compile from there (and I'm afraid this means looking at the [.travis.yml](https://github.com/TrustInSoft/tis-kernel/blob/master/.travis.yml) file again because TIS Kernel targets OCaml 4.05.0 and does not support earlier OCaml versions), then you can look forward to running this C code:

```
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

typedef unsigned __int128 uint128_t;

uint64_t mult_hi(uint64_t x, uint64_t y) {
  uint128_t p = (uint128_t) x * y;
  return (uint64_t)(p >> 64);
}

int main(void) {
  printf("%" PRIu64 "\n", mult_hi(1234567891234567, 7654321987654321));
}
```

Command and result:

```
$ tis-interpreter -machdep gcc_x86_64 uint128.c 
...
512273608685
```

Whereas GCC produces code that produces:

```
$ gcc uint128.c && ./a.out
512273608685
```

**Comment by ysangkok** [comment]
Ah great! Thanks!
