### ISSUE TITLE
Examples commands currently broken

### ISSUE THREAD

**Issue by mmcco** [TrustInSoft/tis-interpreter#3]
It seems that some files have been shuffled around, causing `tis-interpreter/tis-interpreter.sh` to fail when running the example commands given in `tis-interpreter/EXAMPLES.md`. It looks like both the markdown doc and the shell script will have to be changed. I started tweaking the shell script, but I'm off to bed for now. I thought I'd mention it - I'm happy to finish it tomorrow if someone hasn't taken care of it by then.

Best,
Mike

**Comment by pascal-cuoq** [comment]
If you are talking about the example `03_filesystem/main.c`, it is in this state because it is about to be completely revised.

**Comment by technion** [comment]
I don't believe it's a reference to a specific example. I've been trying this out but can't get any of the examples or my own code to run:

    # ../../tis-interpreter.sh example.c
    ../../tis-interpreter.sh: 170: exec: ../../tis-interpreter/bin/frama-c: not found

I've played around with directories and symlinks but haven't identified how it's finding those files.

**Comment by pascal-cuoq** [comment]
@technion This behavior comes from not having followed the steps in [INSTAll.md](https://github.com/TrustInSoft/tis-interpreter/blob/master/INSTALL.md). Alternately, you can obtain a binary snapshot for Linux-x86_64 from the bottom of the [webpage](http://trust-in-soft.com/tis-interpreter/).

**Comment by mmcco** [comment]
> This behavior comes from not having followed the steps in INSTAll.md.

Oh, I see.

That's a slightly odd way of doing things. Usually, `make` gets everything ready to test within the working directory, while `make install` only installs to the system. It doesn't matter much, though.

**Comment by technion** [comment]
Can confirm, this is the part that threw me too. Thank you for your response on this.

**Comment by pascal-cuoq** [comment]
The complexity of the compilation is caused by:

- the dependencies, that most installed distributions do not have out of the box in recent enough versions, so the package is organized to make the creation of easy-to-use binary tarballs easy;
- the fact that tis-interpreter is a modified version of Frama-C, a codebase going back 12 years, that has grown to large proportions, although only a few parts of it are used in tis-interpreter.

Things can be simplified progressively, but the open-source release had to be done at some point.

**Comment by pascal-cuoq** [comment]
(also tis-interpreter is going to continue to evolve quickly in the short term, so traditional distribution packaging of tis-interpreter itself is not the solution. People will still want a binary snapshot, and it's nicer if they can put it where they want (including a homedir for non-root users). Already the binary snapshot I made one week ago is obsolete because it does not contain `tis-mkfs`.

**Comment by technion** [comment]
If it helps with the packing problem, I found the simplest way to build it was in a Docker container. I already worked this way for the Infer analyser, and the Dockerfile I had there was nearly already able to build tis-interpreter.

**Comment by pascal-cuoq** [comment]
@technion That would be nice in more ways that one, the C projects I am hoping to run through tis-interpreter next are [musl](http://www.musl-libc.org/) and [BusyBox](https://www.busybox.net/about.html), which are essential components of [Alpine Linux](http://www.alpinelinux.org/about/), which Docker chose to [move](https://www.brianchristner.io/docker-is-moving-to-alpine-linux/) to as base Linux distribution recently. A cute way to “bootstrap”.
