### ISSUE TITLE
Crash: printf 2GB

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#43]
Source code:
```c
#include <limits.h>
#include <stdio.h>

int main()
{
  printf(">%*d", INT_MAX, 1);
}
```

tis-interpreter (3615ce825dfb8a5e66ba60c0e62e9c2131f1cd2d) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed
Segmentation fault
```

**Comment by pascal-cuoq** [comment]
This is not a stack overflow. You are running into the bug that was fixed by [this commit](https://github.com/ocaml/ocaml/commit/659615c7b100a89eafe6253e7a5b9d84d0e8df74#diff-a97df53e3ebc59bb457191b496c90762).

I have already had to identify this bug for a customer, options range from fixing things in OCaml's source code before compiling OCaml to patching the `tis-interpreter/bin/frama-c` binary (indications below). Or limiting the size of strings to <1GiB until a newer OCaml compiler without this problem arrives (it should be real soon now).

```
$ objdump -d -t ./tis-interpreter/tis-interpreter/bin/frama-c
…
0000000000a5982c <caml_blit_string>:
  a5982c:       48 83 ec 08             sub    $0x8,%rsp
  a59830:       48 89 d0                mov    %rdx,%rax
  a59833:       49 c1 e0 1f             shl    $0x1f,%r8
  a59837:       4c 89 c2                mov    %r8,%rdx
  a5983a:       48 c1 fa 20             sar    $0x20,%rdx
  a5983e:       48 d1 fe                sar    %rsi
  a59841:       48 01 fe                add    %rdi,%rsi
  a59844:       48 d1 f9                sar    %rcx
  a59847:       48 8d 3c 01             lea    (%rcx,%rax,1),%rdi
  a5984b:       e8 10 fd b4 ff          callq  5a9560 <memmove@plt>
  a59850:       b8 01 00 00 00          mov    $0x1,%eax
  a59855:       48 83 c4 08             add    $0x8,%rsp
  a59859:       c3                      retq   
```
In the code for `caml_blit_string`, the `shl    $0x1f,…`, `sar    $0x20,…` sequence is wrong. it amounts to sign-expanding a signed 31-bit unboxed integer as OCaml represents them to a 64-bit register. Replacing the `$0x1f` by `$1` and the `$0x20` by `$2` would fix the bug.

It is too annoying to work around this bug, but we should have limits for precision and width in printf anyway, perhaps I can arbitrarily pick limits below 1GiB and make hide this bug this way.

**Comment by pascal-cuoq** [comment]
Fixed in OCaml 4.03 released recently. Beware that you need something like 14GiB to run your example program.

**Comment by ch3root** [comment]
Does tis-interpreter warn about this programs now? It exhibits UB because the result of printf (INT_MAX+1) doesn't fit into the resulting type (int). That's what I was trying to test with this testcase.

**Comment by pascal-cuoq** [comment]
Depending on the platform, the actual limit for the interpretation of a width (or for the maximum message length, I don't know yet) can be slightly less than `INT_MAX`. On Linux I observed something like `printf(">%*d", 0x7fffff80, 1);` not printing the plentiful spaces one would have expected.

Since the actual useful theorem is that in absence of warnings, tis-interpreter predicts what the program does when compiled with a compiler, not what it should do, I should set a limit, and the limit can be slightly on the safe side and that won't affect the theorem. (There will be a warning for a strange program that was in fact fine. It's okay.)

I need to reverse-engineer the behavior of Glibc's `printf` a bit more before I decide how this limit works.

**Comment by ch3root** [comment]
Like this -- https://sourceware.org/bugzilla/show_bug.cgi?id=17829#c7 ?

**Comment by pascal-cuoq** [comment]
32, heh? Yes, this is what I have observed.

**Comment by ch3root** [comment]
In this case it could be safe to put a smaller limit. C11, 7.21.6.1p15, says that an implementation is not required to support producing more than 4095 per conversion:-)

But in general matching existing systems bug-for-bug could be tricky. Please enjoy #71 :-)

**Comment by pascal-cuoq** [comment]
I know about the 4095 bound, but it's not what we are looking for either : a similar situation is the minimum bound for `INT_MAX`: 5.2.4.2.1 says it's at least 32767 but this 32767 is not the value we want to use, what we want to use is the (ideally documented) value of `INT_MAX` on the target compiler(s).

On the other hand rather than matching bugs in existing compilers (which leaves us with wasted time and an unsound interpreter once the compiler bug gets fixed), the hope is rather to delimit a safe (but hopefully large enough to be useful) space where programs do not hit long-standing won't-be-fixed bugs.

(You have interacted with tis-interpreter long enough to already know all this but I am leaving this position statement for readers that follow your bug reports for entertainment. I know a few.)

**Comment by ch3root** [comment]
Thanks for spelling this out explicitly and clearly.

And it seems I was wrong about 4095 limit. It's per conversion specifier and glibc bug is about total width.

**Comment by ch3root** [comment]
Ok, I've binary-patched frama-c as described above (thanks!). Like this:
```
perl -i -pe 's/(\x49\xc1\xe0)\x1f(\x4c\x89\xc2\x48\xc1\xfa)\x20/$1\x01$2\x02/' tis-interpreter/tis-interpreter/bin/frama-c
```

Crash is gone. Result of `printf` is wrapped. Should this issue be reopened or it's better to file another one?

**Comment by ch3root** [comment]
The bug in OCaml seems bad enough -- at least crashes in random programs written in OCaml caused by untrusted input. Shouldn't be CVE for it?

**Comment by pascal-cuoq** [comment]
Taking care of `printf` is in my pipeline, do not waste time creating a ticket.

Yes, now that I think about it, the OCaml buffer overflow is CVE-worthy. I'll need to make a list of the functions that had this bug so that people can know if they should be concerned. (The pattern of taking and converting a 32-bit unboxed int to a 64-bit size_t was in several functions, that were all fixed in the same commit). I hope to do this within 4h.

**Comment by ch3root** [comment]
Cool, thanks. I guess it's not that urgent.
