### ISSUE TITLE
No warnings: strcpy with overlapping arguments

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#64]
Source code:
```c
#include <string.h>

int main()
{
  char s[1] = "";
  strcpy(s, s);
}
```

tis-interpreter (274be6de79973f11ab62a3c77d0981882734cb2d) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed
[value] done for function main
```

**Comment by ch3root** [comment]
Finer point: AIUI null terminator is included into both the source and the destination objects for the purpose of determining overlap.

C11, 7.24.2.3p2: "The strcpy function copies the string pointed to by s2 (including the terminating null character) into the array pointed to by s1. If copying takes place between objects that overlap, the behavior is undefined."

**Comment by pascal-cuoq** [comment]
I agree that the null character terminator should be included, this is an oversight.

**Comment by ch3root** [comment]
Well, maybe I'm missing something but AFAICT strcpy doesn't catch overlapping at all.

Source code:
```c
#include <string.h>

int main()
{
  char s[] = "abc";
  strcpy(s, s + 1);
}
```

tis-interpreter (274be6de79973f11ab62a3c77d0981882734cb2d) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed
[value] done for function main
```

**Comment by pascal-cuoq** [comment]
Oh yes, sorry, I thought it was done. The fact overlap detection doesn't exist at all in `strcpy` is the oversight then. (`strcpy` was the last function implemented in a rush before the push to GitHub.)

It's funny because I implemented it just now that detected the problem in the second example but not in the first one. Fortunately the first test was already available, so still thank you for that test.
