### ISSUE TITLE
signed overflow.

### ISSUE THREAD

**Issue by kroeckx** [TrustInSoft/tis-interpreter#98]
Hi,

I'm getting:
```
crypto/asn1/ameth_lib.c:66:[kernel] warning: signed overflow. assert (*a)->pkey_id-(*b)->pkey_id ≤ 2147483647;
                  stack: ameth_cmp :: crypto/asn1/ameth_lib.c:69 <-
                         ameth_cmp_BSEARCH_CMP_FN :: crypto/objects/obj_dat.c:600 <-
                         OBJ_bsearch_ex_ :: crypto/objects/obj_dat.c:581 <-
[...]
crypto/asn1/ameth_lib.c:66:[value] warning: The following sub-expression cannot be evaluated:
                 (*a)->pkey_id - (*b)->pkey_id
                 
                 All sub-expressions with their values:
                 int  (*a)->pkey_id ∈ {0}
                 int  (*b)->pkey_id ∈ [-2147483648..2147483647]
                 EVP_PKEY_ASN1_METHOD const *  *a ∈ {{ &tmp }}
                 EVP_PKEY_ASN1_METHOD const *  *b ∈ {{ &dsa_asn1_meths[3] }}
                 EVP_PKEY_ASN1_METHOD const * const *  a ∈ {{ &t }}
                 EVP_PKEY_ASN1_METHOD const * const *  b ∈ {{ &standard_methods[6] }}
```

What I don't understand is why it thinks there is an overflow.  If b points to dsa_asn1_meths[3], (*b)->pkey_id should be EVP_PKEY_DSA3 = NID_dsaWithSHA1 = 113.  I don't understand why it's saying it could have any value.

(I already made sure that dsa_asn1_meths has a fixed size of 5, not commited yet, same for rsa_asn1_meths with size of 2.)

**Comment by kroeckx** [comment]
It was missing the file where those variables get initialized ...

**Comment by pascal-cuoq** [comment]
The “following sub-expression cannot be evaluated” warning does not usually correspond to something wrong in the program, but to tis-interpreter indicating that, although it is working in a mode where each variable should be knows exactly at each point, suddenly an expression did not evaluate to a single value.

This can be because the program is doing something that tis-interpreter cannot model, like `(uintptr_t) &a + (uintptr_t) &b`, but one common cause is a missing file (and the message should be more explicit in this case).

Regarding `dsa_asn1_meths`, a definition such as that [here](https://github.com/openssl/openssl/blob/d2e9e320186f0917cc940f46bdf1a7e4120da9b0/crypto/dsa/dsa_ameth.c#L512-L567) is fine. The size (5) of the array is determined from the initializer. you should have to make the size explicit in the definition.
