### ISSUE TITLE
No char_equal_ignore_case()

### ISSUE THREAD

**Issue by kroeckx** [TrustInSoft/tis-interpreter#99]
common_helpers/common_missing.c has:
```
// from string.c
int char_equal_ignore_case(char c1, char c2);

// Should be in strings.h + strings.c:
/*@ assigns \result \from s1[0 .. n-1], s2[0 ..n-1]; */
int strncasecmp (const char *s1, const char *s2, size_t n) {
  for ( ; n != 0 && *s1 && *s2; n--, s1++, s2++) {
    int res = char_equal_ignore_case(*s1,*s2);
    if(res != 0) return res;
  }
  return 0;
}
```

But there is no implementation of that char_equal_ignore_case.

**Comment by pascal-cuoq** [comment]
In discussions with @regehr about the efficiency of tis-interpreter, I realized that the overhead of very short functions was higher-than-average compared to compilers, which can inline these and reduce the function call overhead to literally zero.

So I manually inlined this function inside `strcasecmp` in order to improve the interpretation time of that function. Sorry.

I have revamped both `strcasecmp` and `strncasecmp` now. These are always tricky to get right but I hope that https://github.com/TrustInSoft/tis-interpreter/commit/7d9e6bc87e5248d704d0502807429c93bb87b42d will work for you.
